import plot_kmeans_example as pke
import tfidf as tf
import rel_post_20news as rp2n
import document_clustering as dc
import noise_analysis as na
import plot_ward_structured_vs_unstructured as pwsvu
print("*"*80,"\n\t\tNon-related lab files\n", "*"*80)
import rel_post_01 as rp1
import topics_extraction_with_nmf_lda as tewnl
